
package com.aonaware.services.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountCheatServiceSoap", targetNamespace = "http://services.aonaware.com/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountCheatServiceSoap {


    /**
     * Returns solutions to the Countdown word game
     * 
     * @param anagram
     * @return
     *     returns com.aonaware.services.webservices.ArrayOfString
     */
    @WebMethod(operationName = "LetterSolutions", action = "http://services.aonaware.com/webservices/LetterSolutions")
    @WebResult(name = "LetterSolutionsResult", targetNamespace = "http://services.aonaware.com/webservices/")
    @RequestWrapper(localName = "LetterSolutions", targetNamespace = "http://services.aonaware.com/webservices/", className = "com.aonaware.services.webservices.LetterSolutions")
    @ResponseWrapper(localName = "LetterSolutionsResponse", targetNamespace = "http://services.aonaware.com/webservices/", className = "com.aonaware.services.webservices.LetterSolutionsResponse")
    public ArrayOfString letterSolutions(
        @WebParam(name = "anagram", targetNamespace = "http://services.aonaware.com/webservices/")
        String anagram);

    /**
     * Returns solutions to the Countdown word game with a minimum letter count
     * 
     * @param anagram
     * @param minLetters
     * @return
     *     returns com.aonaware.services.webservices.ArrayOfString
     */
    @WebMethod(operationName = "LetterSolutionsMin", action = "http://services.aonaware.com/webservices/LetterSolutionsMin")
    @WebResult(name = "LetterSolutionsMinResult", targetNamespace = "http://services.aonaware.com/webservices/")
    @RequestWrapper(localName = "LetterSolutionsMin", targetNamespace = "http://services.aonaware.com/webservices/", className = "com.aonaware.services.webservices.LetterSolutionsMin")
    @ResponseWrapper(localName = "LetterSolutionsMinResponse", targetNamespace = "http://services.aonaware.com/webservices/", className = "com.aonaware.services.webservices.LetterSolutionsMinResponse")
    public ArrayOfString letterSolutionsMin(
        @WebParam(name = "anagram", targetNamespace = "http://services.aonaware.com/webservices/")
        String anagram,
        @WebParam(name = "minLetters", targetNamespace = "http://services.aonaware.com/webservices/")
        int minLetters);

}
