
package com.aonaware.services.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CountCheat Web Service - Returns solutions to Countdown problems
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CountCheatService", targetNamespace = "http://services.aonaware.com/webservices/", wsdlLocation = "http://services.aonaware.com/CountCheatService/CountCheatService.asmx?wsdl")
public class CountCheatService
    extends Service
{

    private final static URL COUNTCHEATSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTCHEATSERVICE_EXCEPTION;
    private final static QName COUNTCHEATSERVICE_QNAME = new QName("http://services.aonaware.com/webservices/", "CountCheatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://services.aonaware.com/CountCheatService/CountCheatService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTCHEATSERVICE_WSDL_LOCATION = url;
        COUNTCHEATSERVICE_EXCEPTION = e;
    }

    public CountCheatService() {
        super(__getWsdlLocation(), COUNTCHEATSERVICE_QNAME);
    }

    public CountCheatService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTCHEATSERVICE_QNAME, features);
    }

    public CountCheatService(URL wsdlLocation) {
        super(wsdlLocation, COUNTCHEATSERVICE_QNAME);
    }

    public CountCheatService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTCHEATSERVICE_QNAME, features);
    }

    public CountCheatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountCheatService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountCheatServiceSoap
     */
    @WebEndpoint(name = "CountCheatServiceSoap")
    public CountCheatServiceSoap getCountCheatServiceSoap() {
        return super.getPort(new QName("http://services.aonaware.com/webservices/", "CountCheatServiceSoap"), CountCheatServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountCheatServiceSoap
     */
    @WebEndpoint(name = "CountCheatServiceSoap")
    public CountCheatServiceSoap getCountCheatServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.aonaware.com/webservices/", "CountCheatServiceSoap"), CountCheatServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTCHEATSERVICE_EXCEPTION!= null) {
            throw COUNTCHEATSERVICE_EXCEPTION;
        }
        return COUNTCHEATSERVICE_WSDL_LOCATION;
    }

}
